version: '3'
services:
  api:
    container_name: quiz_test_api
    ports:
      - 3000:3000
    environment: 
      - PGUSER=rhyspeter
      - PGHOST=db
      - PGPASSWORD=password
      - PGDATABASE=quiz_test
      - PGPORT=5432
      - NODE_ENV=test
    depends_on: 
      - db
    tty: true
  db:
    container_name: quiz_test_db
    expose:
      - "5432"
    volumes:
      - "test_db:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=quiz_test
      - POSTGRES_USER=rhyspeter
      - POSTGRES_PASSWORD=password
volumes:
  test_db: